version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "21:45"
    timezone: "Europe/Brussels"
  labels:
    - "gha-deps"
  reviewers:
    - "MatthiasValvekens"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
    time: "22:15"
    timezone: "Europe/Brussels"
  labels:
    - "python-deps"
  reviewers:
    - "MatthiasValvekens"