sudo: false
language: c
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]$/
matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "2.6"
    - os: linux
      dist: bionic
      language: python
      python: "2.7"
    - os: linux
      dist: trusty
      language: python
      python: "3.2"
    - os: linux
      dist: trusty
      language: python
      python: "3.3"
    - os: linux
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      dist: xenial
      language: python
      python: "pypy"
script:
  - python run.py deps
  - python run.py ci
