sudo: false
language: c
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]$/
matrix:
  include:
    - os: osx
      python: "2.6"
      env: TRAVIS_PYTHON_VERSION=2.6
    - os: osx
      python: "2.7"
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      python: "3.5"
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      python: "pypy"
      env: TRAVIS_PYTHON_VERSION=pypy
    - os: linux
      language: python
      python: "2.6"
    - os: linux
      language: python
      python: "2.7"
    - os: linux
      language: python
      python: "3.2"
    - os: linux
      language: python
      python: "3.3"
    - os: linux
      language: python
      python: "3.4"
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "pypy"
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; then
            brew update;
            brew install pypy;
            /usr/local/bin/pip_pypy install flake8;
            /usr/local/bin/pip_pypy install https://github.com/wbond/asn1crypto/archive/master.zip;
            /usr/local/bin/pip_pypy install https://github.com/wbond/oscrypto/archive/master.zip;
            export PYTHON_BIN=/usr/local/bin/pypy;
        else
            if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then
                brew update;
                brew install python3;
                /usr/local/bin/pip3 install flake8;
                /usr/local/bin/pip3 install https://github.com/wbond/asn1crypto/archive/master.zip;
                /usr/local/bin/pip3 install https://github.com/wbond/oscrypto/archive/master.zip;
                export PYTHON_BIN=/usr/local/bin/python3;
            else
                if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
                    curl --silent --show-error https://bootstrap.pypa.io/get-pip.py | sudo /usr/bin/python2.7;
                    sudo /usr/bin/python2.7 -W ignore -c "import pip; pip.main(['--disable-pip-version-check', '--quiet', 'install', 'flake8'])";
                    sudo /usr/bin/python2.7 -W ignore -c "import pip; pip.main(['--disable-pip-version-check', '--quiet', 'install', 'https://github.com/wbond/asn1crypto/archive/master.zip'])";
                    sudo /usr/bin/python2.7 -W ignore -c "import pip; pip.main(['--disable-pip-version-check', '--quiet', 'install', 'https://github.com/wbond/oscrypto/archive/master.zip'])";
                    export PYTHON_BIN=/usr/bin/python2.7;
                else
                    curl --silent --show-error -o asn1crypto-master.zip https://github.com/wbond/asn1crypto/archive/master.zip;
                    unzip ans1crypto-master.zip;
                    cd asn1crypto-master;
                    sudo /usr/bin/python2.6 setup.py install clean;
                    curl --silent --show-error -o oscrypto-master.zip https://github.com/wbond/oscrypto/archive/master.zip;
                    unzip ans1crypto-master.zip;
                    cd oscrypto-master;
                    sudo /usr/bin/python2.6 setup.py install clean;
                    export PYTHON_BIN=/usr/bin/python2.6;
                fi
            fi
        fi
    else
        python -c "import sys,pip; pip.main(['install', '--upgrade', 'pip' + ('==7.1.2' if sys.version_info[0:2] == (3, 2) else '')])";
        pip install flake8;
        pip install https://github.com/wbond/asn1crypto/archive/master.zip;
        pip install https://github.com/wbond/oscrypto/archive/master.zip;
        export PYTHON_BIN=python;
    fi
script:
  - $PYTHON_BIN run.py ci
