name: Lint

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install isort black
      - name: Check import order
        run: isort --profile black --line-length 80 --check pyhanko_certvalidator tests
      - name: Run Black
        run: black -S --line-length 80 --check pyhanko_certvalidator tests
